### ISSUE TITLE
Remove client if an error occurs at recv/send

### ISSUE THREAD

**Issue by u413-284-si** [u413-284-si/webserv#75]
use shallCloseConnection boolean

based on eval

**Comment by gwolf-011235** [comment]
> use shallCloseConnection boolean

Why?

If recv errors with -1 we close fd and set connection status closed: 
- connectionReceiveHeader() Server.cpp:752
- connectionReceiveBody() Server.cpp:862

If send errors with -1 we close fd and set connection status closed: 
- connectionSendResponse() Server.cpp:972

We could additionally remove the event from epoll, although this should happen automatically. 

From [man epoll](https://man7.org/linux/man-pages/man7/epoll.7.html): 
Will closing a file descriptor cause it to be removed from all epoll interest lists?
Yes, but be aware of the following point. [~= if you have two refrences it won't be removed]

**Comment by u413-284-si** [comment]
Yes, you are right, this point is already handled. Was not fully aware of the closing of fds when an error occurs with recv/send. This can be closed, all the better!
