### ISSUE TITLE
Implement method POST

### ISSUE THREAD

**Issue by gwolf-011235** [u413-284-si/webserv#81]
Creates a resource.

More specific RFC 9110 Section 9.3.3 [POST](https://www.rfc-editor.org/rfc/rfc9110.html#name-post)

The creation of a resource is highly dependent on context. We decided to interpret it as "create a file with the request body as content".

**Comment by u413-284-si** [comment]
Sample "201 Created" response:

HTTP/1.1 201 Created
Location: https://api.example.com/resources/12345
Content-Type: application/json
Content-Length: 85

{
    "id": 12345,
    "name": "New Resource",
    "status": "created"
}
